### ISSUE TITLE
Crashes randomly

### ISSUE THREAD

**Issue by stasadance** [CalypsoToolz/FPAgar#5]
After a certain amount of time, not sure why, it stops letting people in and the leaderboard is blank. I have to restart it to fix it.

**Comment by CalypsoToolz** [comment]
@Stasadance whether there is an error in the logs?

**Comment by stasadance** [comment]
@Calyps0 Sadly no error. I have it logging ALL and it still connects users even shows packets, but simply cant play and leaderboard is blank.

**Comment by stasadance** [comment]
I found the issue. In a tick sometimes it throws some **concurrent exception** and kills the tick thread causing nothing to happen but the leaderboard packet still works.

**Comment by stasadance** [comment]
Exception in thread "Tick Worker - #1" java.util.ConcurrentModificationException

**Comment by stasadance** [comment]
I believe the error is simply due to an exception being thrown about the id which also happens to kill the tick thread. Simply removing it seems to help.
